name: Build and Test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@1.0.5
        id: versioning
        with:
          releaseType: patch
          incrementPerCommit: false
          github_token: ${{ secrets.TOKEN }}

      - name: Next Release Number
        id: next_version
        run: |
          echo ${{ steps.versioning.outputs.version }}
          ls 123456

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Windows SDK
        run: choco install windows-sdk-10.1 --version=10.1.18362.1 --yes

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Read version
        id: version
        run: |
          $version = Get-Content -Path ./version.txt -Raw
          $version = $version.Trim()
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          Write-Host "Package version: $version"
        shell: pwsh
         
      - name: Install Cake
        run: dotnet tool install --global Cake.Tool --version 2.2.0

      - name: Add .NET tools to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Run Cake build
        run: dotnet cake build.cake
        env:
          NUGET_API_KEY: ${{ secrets.TOKEN }}
          PACKAGE_VERSION: ${{ steps.versioning.outputs.version }}
